name: Invoke Lambda with Variable

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'

jobs:
  call-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Call Lambda Function using Function URL
        run: |
          JSON_PAYLOAD=$(printf '{"name": "%s"}' "${{ github.event.inputs.name }}")

          curl -X POST ${{ secrets.LAMBDA_FUNCTION_URL }} \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"'
