name: Invoke Lambda with Variable

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'

jobs:
  call-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Call Lambda Function using Function URL
        run: |
          NAME_INPUT="${{ github.event.inputs.name }}"
          JSON_PAYLOAD="{\"name\": \"$NAME_INPUT\"}"

          echo "Sending payload: $JSON_PAYLOAD"

          curl -X POST ${{ secrets.LAMBDA_FUNCTION_URL }} \
            -H 'content-type: application/json' \
            -d '{ "name": "test" }'
